<%@ Page Title="" Language="C#" MasterPageFile="~/NLMain.master" AutoEventWireup="true" CodeFile="ExpiryItem.aspx.cs" Inherits="Modules_Stock_ExpiryItem" %>
<%@ Register Assembly="Telerik.Web.UI" Namespace="Telerik.Web.UI" TagPrefix="telerik" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">


    <telerik:RadAjaxManager ID="RadAjaxManager1" runat="server">
    </telerik:RadAjaxManager>

    <div class="row">
        <div class="panel-body"></div>
    </div>
    <div class="row">

        <telerik:RadGrid ID="RadGrid1" runat="server" AllowFilteringByColumn="True" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True" DataSourceID="SqlDataSource1" ShowGroupPanel="True" AllowAutomaticDeletes="True" AllowAutomaticInserts="True" AllowAutomaticUpdates="True" PageSize="20" CellSpacing="-1" GridLines="Both">
<GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>
            <ExportSettings>
                <Pdf PaperSize="A4">
                </Pdf>
            </ExportSettings>
            <ClientSettings AllowDragToGroup="True">
            </ClientSettings>
            <MasterTableView AutoGenerateColumns="False" DataKeyNames="Item_Batch_Id" DataSourceID="SqlDataSource1" CommandItemDisplay="Top" Font-Size="Larger" BorderColor="Red" >
                <Columns>


               <%--     <telerik:GridDateTimeColumn SortExpression="Mfg" DataType="System.DateTime" PickerType="DatePicker" ItemStyle-Width="100" HeaderStyle-Width="100" EditDataFormatString="dd/mm/yyyy"  HeaderText="DateTimeYourColumnName"  DataFormatString="{0:dd/mm/yyyy}"  DataField="Mfg" UniqueName="Mfg">
</telerik:GridDateTimeColumn>--%>



                    <telerik:GridTemplateColumn DataField="Item_Batch_Id" DataType="System.Int64" FilterControlAltText="Filter Item_Batch_Id column" HeaderText="Item_Batch_Id" SortExpression="Item_Batch_Id" UniqueName="Item_Batch_Id" Visible="false" >
                       <%-- <EditItemTemplate>
                            <asp:TextBox ID="Item_Batch_IdTextBox" runat="server" Text='<%# Bind("Item_Batch_Id") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Item_Batch_IdLabel" runat="server" Text='<%# Eval("Item_Batch_Id") %>'></asp:Label>
                        </ItemTemplate>--%>
                    </telerik:GridTemplateColumn>
                    <telerik:GridTemplateColumn DataField="Item_Code" FilterControlAltText="Filter Item_Code column" HeaderText="Item Code" HeaderStyle-Font-Bold="true" ItemStyle-Font-Bold="true"  SortExpression="Item_Code" UniqueName="Item_Code" >
                        <EditItemTemplate >

                              <asp:TextBox ID="Item_CodeTextBox" CssClass="form-control" runat="server" Text='<%# Bind("Item_Code") %>' Font-Size="Large"></asp:TextBox>
                           
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Item_CodeLabel" runat="server" Text='<%# Eval("Item_Code") %>'></asp:Label>
                           
                        </ItemTemplate>

<HeaderStyle Font-Bold="True"></HeaderStyle>

<ItemStyle Font-Bold="True"></ItemStyle>
                    </telerik:GridTemplateColumn>



                    <telerik:GridTemplateColumn DataField="BatchNO" HeaderStyle-Font-Bold="true" ItemStyle-Font-Bold="true" FilterControlAltText="Filter BatchNO column" HeaderText="Batch No" SortExpression="BatchNO" UniqueName="BatchNO" >
                        <EditItemTemplate>
                            
                                  <asp:TextBox ID="BatchNOTextBox" CssClass="form-control" runat="server" Text='<%# Bind("BatchNO") %>'></asp:TextBox>
                          

                          
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="BatchNOLabel"   runat="server" Text='<%# Eval("BatchNO") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>
                    <telerik:GridTemplateColumn DataField="Qty" HeaderStyle-Font-Bold="true" ItemStyle-Font-Bold="true" DataType="System.Int64" FilterControlAltText="Filter Qty column" HeaderText="Qty" SortExpression="Qty" UniqueName="Qty">
                        <EditItemTemplate>
                            <asp:TextBox ID="QtyTextBox" CssClass="form-control" runat="server" Text='<%# Bind("Qty") %>' Width="20%" TextMode="Number"></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="QtyLabel" runat="server" Text='<%# Eval("Qty") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>
                    <telerik:GridTemplateColumn DataField="Mfg" HeaderStyle-Font-Bold="true" ItemStyle-Font-Bold="true" DataType="System.DateTime" FilterControlAltText="Filter Mfg column" HeaderText="Mfg" SortExpression="Mfg" UniqueName="Mfg">
                        <EditItemTemplate>
                           <%-- <asp:TextBox ID="MfgTextBox" runat="server" Text='<%# Bind("Mfg") %>'></asp:TextBox>--%>

                            <telerik:RadDatePicker RenderMode="Lightweight" ID="BirthDatePicker" runat="server" MinDate="1/1/1900" DbSelectedDate='<%# Bind("Mfg") %>'  Width="100%"
                                                    TabIndex="4">
                                                </telerik:RadDatePicker>



                        </EditItemTemplate>
                        <ItemTemplate>
                              <telerik:RadDatePicker RenderMode="Lightweight" ID="BirthDatePicker" runat="server" MinDate="1/1/1900" DbSelectedDate='<%# Bind("Mfg") %>'
                                                    TabIndex="4">
                                                </telerik:RadDatePicker>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>
                    <telerik:GridTemplateColumn DataField="Exp" HeaderStyle-Font-Bold="true" ItemStyle-Font-Bold="true" DataType="System.DateTime" FilterControlAltText="Filter Exp column" HeaderText="Exp" SortExpression="Exp" UniqueName="Exp">
                        <EditItemTemplate>

                               <telerik:RadDatePicker RenderMode="Lightweight" ID="BirthDatePicker1" runat="server" MinDate="1/1/1900" DbSelectedDate='<%# Bind("Exp") %>'  Width="100%"
                                                    TabIndex="4">
                                                </telerik:RadDatePicker>
                            
                        </EditItemTemplate>
                        <ItemTemplate>
                            <telerik:RadDatePicker RenderMode="Lightweight" ID="BirthDatePicker1" runat="server" MinDate="1/1/1900" DbSelectedDate='<%# Bind("Exp") %>'
                                                    TabIndex="4">
                                                </telerik:RadDatePicker>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>
                    <telerik:GridTemplateColumn DataField="Remarks" HeaderStyle-Font-Bold="true" ItemStyle-Font-Bold="true" FilterControlAltText="Filter Remarks column" HeaderText="Remarks" SortExpression="Remarks" UniqueName="Remarks">
                        <EditItemTemplate>
                            <asp:TextBox ID="RemarksTextBox" Rows="5" Columns="40" CssClass="form-control" runat="server" Text='<%# Bind("Remarks") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="RemarksLabel"  runat="server" Text='<%# Eval("Remarks") %>'></asp:Label>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>
                </Columns>
                <EditItemStyle Font-Bold="True" HorizontalAlign="Justify" VerticalAlign="Middle"  />
            </MasterTableView>
        </telerik:RadGrid>

        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:DBCon %>" DeleteCommand="DELETE FROM [Item_Batch_Expriy] WHERE [Item_Batch_Id] = @Item_Batch_Id" InsertCommand="INSERT INTO [Item_Batch_Expriy] ([Item_Code], [BatchNO], [Qty], [Mfg], [Exp], [Remarks]) VALUES (@Item_Code, @BatchNO, @Qty, @Mfg, @Exp, @Remarks)" SelectCommand="SELECT * FROM [Item_Batch_Expriy] ORDER BY Item_Batch_Id" UpdateCommand="UPDATE [Item_Batch_Expriy] SET [Item_Code] = @Item_Code, [BatchNO] = @BatchNO, [Qty] = @Qty, [Mfg] = @Mfg, [Exp] = @Exp, [Remarks] = @Remarks WHERE [Item_Batch_Id] = @Item_Batch_Id">
            <DeleteParameters>
                <asp:Parameter Name="Item_Batch_Id" Type="Int64" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Item_Code" Type="String" />
                <asp:Parameter Name="BatchNO" Type="String" />
                <asp:Parameter Name="Qty" Type="Int64" />
                <asp:Parameter Name="Mfg" Type="DateTime" />
                <asp:Parameter Name="Exp" Type="DateTime" />
                <asp:Parameter Name="Remarks" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Item_Code" Type="String" />
                <asp:Parameter Name="BatchNO" Type="String" />
                <asp:Parameter Name="Qty" Type="Int64" />
                <asp:Parameter Name="Mfg" Type="DateTime" />
                <asp:Parameter Name="Exp" Type="DateTime" />
                <asp:Parameter Name="Remarks" Type="String" />
                <asp:Parameter Name="Item_Batch_Id" Type="Int64" />
            </UpdateParameters>
        </asp:SqlDataSource>

    </div>
        






</asp:Content>

